[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[extra]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[targets]
test = ["BenchmarkTools", "SafeTestsets"]